In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset_dir = "Datasets/houseprices_ready.csv"
df = pd.read_csv(dataset_dir, index_col=None)

In [3]:
df = pd.read_csv(dataset_dir, index_col=0)
df = df.fillna(df.mean())
df.head(10)

,AboveMedianPrice,LotArea,OverallQual,OverallCond,TotalBsmtSF,FullBath,HalfBath,BedroomAbvGr,TotRmsAbvGrd,Fireplaces,GarageArea
0,1,8450,7,5,856,2,1,3,8,0,548
1,1,9600,6,8,1262,2,0,3,6,1,460
2,1,11250,7,5,920,2,1,3,6,1,608
3,0,9550,7,5,756,1,0,3,7,1,642
4,1,14260,8,5,1145,2,1,4,9,1,836
5,0,14115,5,5,796,1,1,1,5,0,480
6,1,10084,8,5,1686,2,0,3,7,1,636
7,1,10382,7,6,1107,2,1,3,7,2,484
8,0,6120,7,5,952,2,0,2,8,2,468
9,0,7420,5,6,991,1,0,2,5,2,205

In [4]:
np.linalg.svd(df)

(array([[-1.53081196e-02,  1.45079014e-02, -2.32068051e-02, ...,
         -3.35220872e-02,  3.49914419e-04, -3.47744543e-03],
        [-1.74144647e-02,  2.29214697e-02,  9.88483874e-03, ...,
         -1.23398598e-02,  2.19922267e-02,  2.32257372e-02],
        [-2.03519171e-02,  1.14655257e-02, -2.70451309e-02, ...,
         -4.50584741e-03, -2.66230257e-02, -2.94272741e-02],
        ...,
        [-1.63900592e-02,  1.83334968e-02,  3.05509903e-02, ...,
          9.88133772e-01, -9.38739056e-04,  1.16748913e-03],
        [-1.75953392e-02,  1.46818866e-02,  2.82481389e-02, ...,
         -6.93092829e-04,  9.96859869e-01, -2.55139765e-03],
        [-1.80112832e-02,  1.98440055e-02,  3.31666837e-02, ...,
          1.58172354e-03, -2.47827416e-03,  9.93673864e-01]]),
 array([5.55052656e+05, 3.17255152e+04, 7.21213806e+03, 1.33006716e+02,
        5.37139205e+01, 3.98186651e+01, 2.30014840e+01, 1.95631595e+01,
        1.75780472e+01, 1.59871921e+01, 1.08587665e+01]),
 array([[-2.94718797e-05, -9.97965435e-01, -3.12513091e-04,
         -2.78932168e-04, -5.84207517e-02, -8.16932296e-05,
         -1.95147895e-05, -1.48185312e-04, -3.41101020e-04,
         -3.89877396e-05, -2.55280800e-02],
        [ 4.22197966e-04, -6.37477956e-02,  4.68663927e-03,
          3.79877781e-03,  9.21199787e-01,  1.16870269e-03,
          2.58307349e-04,  1.95812868e-03,  4.64038840e-03,
          4.19021802e-04,  3.83749425e-01],
        [-5.88810263e-04,  1.09792952e-03, -3.88179914e-03,
         -2.84404388e-03,  3.84648731e-01, -1.17855305e-03,
         -7.66691927e-04, -1.54771941e-03, -4.10812485e-03,
         -1.86786643e-04, -9.23038114e-01],
        [ 4.56156227e-03,  5.50439433e-05, -4.06157213e-01,
         -6.12809175e-01,  4.69049831e-03, -1.11904322e-01,
         -4.75272492e-02, -3.05288153e-01, -5.92633340e-01,
         -1.35267182e-02,  8.88263251e-03],
        [-9.80729664e-02,  7.19194098e-06,  1.12605303e-02,
          7.28815653e-01,  2.54604224e-04, -1.31675154e-01,
         -1.03146662e-01, -2.20948007e-01, -6.13342695e-01,
         -7.80779021e-02,  1.24555886e-03],
        [-1.89898395e-01, -1.26642205e-05, -8.59440647e-01,
          2.27966564e-01,  1.03729783e-03, -1.19101568e-01,
         -9.48710016e-02,  2.62051117e-01,  2.50107682e-01,
         -1.37533625e-01,  2.17148473e-03],
        [ 1.49573861e-01, -1.15958294e-05, -1.93821470e-01,
          1.44534037e-01,  1.46546832e-05, -1.53408010e-01,
          2.08702582e-01, -3.85180228e-01,  1.76463398e-01,
          8.20107850e-01, -2.50328919e-06],
        [-8.71361809e-02,  5.43233476e-06, -3.04074124e-03,
          2.37199027e-02, -2.62685175e-05, -6.86629923e-02,
         -1.09671485e-01, -7.85890293e-01,  4.13344467e-01,
         -4.31990381e-01, -2.71369261e-04],
        [ 1.50935988e-01, -3.60682042e-06, -6.94388880e-02,
          2.38971839e-02, -2.96862840e-04,  5.52544948e-01,
         -7.83232021e-01, -6.86278146e-02,  1.28576938e-02,
          2.19526735e-01, -4.31144675e-05],
        [ 6.00069721e-01, -3.65172505e-07, -2.30810908e-01,
          1.37941518e-01,  2.76136208e-04,  5.38235184e-01,
          4.61905118e-01, -8.37466689e-02, -7.01348859e-02,
         -2.29409616e-01, -2.93974962e-04],
        [-7.35845475e-01,  1.12878067e-06, -2.37217244e-02,
         -1.58002636e-02,  1.20928826e-04,  5.76801070e-01,
          3.09366168e-01, -1.07672838e-01, -5.41006721e-02,
          1.21621650e-01,  7.15165396e-05]]))